var i18n = window.i18n();
i18n.setLocale('vi');
i18n.setMessages('messages', 'vi', {
  "Teeth": "Răng",
  "Salivary glands": "Tuyến nước bọt",
  "Tongue": "Lưỡi",
  "Esophagus": "Thực quản",
  "Gallbladder": "Túi mật",
  "Liver": "Gan",
  "Stomach": "Dạ dày",
  "Pancreas": "Tụy",
  "Small-intestine": "Ruột non",
  "Duodenum": "Ruột tá",
  "Appendix": "Ruột thừa",
  "Anus": "Hậu môn",
  "Rectum": "Ruột thẳng",
  "Colon-Large intestine": "Ruột kết-ruột già",
  "Click on “play” to start. Click on the figure to name the organs.": "Nhấn ► để bắt đầu. Nhấn vào nhân vật để hiện tên các cơ quan.",
  "Undigested food": "Thức ăn\nkhông tiêu hóa",
  "Nutrients": "Chất dinh dưỡng",
  "Capillary": "Mao mạch",
  "To the organs": "Đến các cơ quan",
  "Undigested materials": "Vật chất không tiêu hóa",
  "Faeces": "Phân",
  "Mastication and saliva secretion": "Nhai và tiết nước bọt",
  "Esophageal transit": "Đi qua thực quản",
  "Food is mixed with gastric juices": "Thức ăn được trộn với dịch vị",
  "Pancreas and gallbladder release bile and pancreatic juice": "Tụy và túi mật tiết mật và dịch tụy",
  "Chyme is mixed with digestive juices": "Nhũ trấp được trộn với dịch tiêu hóa",
  "Nutrient absorption": "Hấp thụ chất dinh dưỡng",
  "Dehydration then excretion of the indigestible component of food": "Loại nước sau đó bài tiết thành phần thức ăn không thể tiêu hóa",
}, 'nplurals=1; plural=0;');
